sonar.organization=univers42
sonar.projectKey=Univers42_track-binocle
sonar.projectName=track-binocle

sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.tests=
sonar.inclusions=**/*.js,**/*.ts,**/*.mjs,**/*.astro,**/*.css,**/*.html,**/*.sql,**/*.yml,**/*.yaml,**/*.md
sonar.exclusions=**/node_modules/**,**/.git/**,**/.vscode/**,audit/**,infrastructure/**,vendor/**,models/**,**/dist/**,**/build/**,**/.astro/**,**/coverage/**,**/*.min.js,**/*.min.css

sonar.sourceEncoding=UTF-8
