#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-.env}"
FORCE="${FORCE:-0}"

if [[ -f "$ENV_FILE" && "$FORCE" != "1" ]]; then
  echo "Error: $ENV_FILE already exists. Use FORCE=1 to overwrite." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "Error: openssl is required but not installed." >&2
  exit 1
fi

b64url() {
  openssl base64 -A | tr '+/' '-_' | tr -d '='
  return 0
}

gen_alnum() {
  local length="$1"
  local out=""
  while [[ "${#out}" -lt "$length" ]]; do
    out+="$(openssl rand -base64 48 | tr -dc 'A-Za-z0-9')"
  done
  printf '%s' "${out:0:length}"
  return 0
}

jwt_hs256() {
  local secret="$1"
  local role="$2"
  local iat exp header payload sig

  iat="$(date +%s)"
  exp="$((iat + 157680000))" # 5 years

  header='{"alg":"HS256","typ":"JWT"}'
  payload=$(printf '{"role":"%s","iss":"supabase","iat":%s,"exp":%s}' "$role" "$iat" "$exp")

  local h p
  h="$(printf '%s' "$header" | b64url)"
  p="$(printf '%s' "$payload" | b64url)"
  sig="$(printf '%s' "$h.$p" | openssl dgst -sha256 -hmac "$secret" -binary | b64url)"

  printf '%s.%s.%s' "$h" "$p" "$sig"
  return 0
}

POSTGRES_USER="postgres"
POSTGRES_PASSWORD="$(gen_alnum 24)"
POSTGRES_DB="postgres"

JWT_SECRET="$(openssl rand -hex 32)"
VAULT_ENC_KEY="$(openssl rand -hex 16)"
MINIO_ROOT_PASSWORD="$(openssl rand -hex 16)"

ANON_KEY="$(jwt_hs256 "$JWT_SECRET" "anon")"
SERVICE_ROLE_KEY="$(jwt_hs256 "$JWT_SECRET" "service_role")"

DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
PGRST_DB_URI="${DATABASE_URL}"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# For local self-hosting only. Do not commit this file.

# Core database connection used by multiple services
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
DATABASE_URL=${DATABASE_URL}
PGRST_DB_URI=${PGRST_DB_URI}

# Kong key-auth credentials = the JWT themselves
# supabase-js sends the same value as both apikey header (key-auth) and
# Authorization: Bearer (jwt plugin), so they must be valid JWTs.
KONG_PUBLIC_API_KEY=${ANON_KEY}
KONG_SERVICE_API_KEY=${SERVICE_ROLE_KEY}
KONG_CORS_ORIGIN_APP=http://localhost:3000
KONG_CORS_ORIGIN_PLAYGROUND=http://localhost:3100
KONG_CORS_ORIGIN_STUDIO=http://localhost:3001
KONG_CORS_ORIGIN_FRONTEND=http://localhost:5173

# GoTrue
API_EXTERNAL_URL=http://localhost:8000/auth/v1
GOTRUE_SITE_URL=http://localhost:5173
GOTRUE_URI_ALLOW_LIST=http://localhost:5173/**
JWT_SECRET=${JWT_SECRET}

# PostgREST
PGRST_DB_SCHEMA=public
PGRST_DB_ANON_ROLE=anon

# Realtime (dlesieur/realtime-agnostic)
# Connection vars are set in docker-compose.yml environment: block.
RUST_LOG=info

# Supabase API keys (legacy HS256 JWTs)
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# MinIO
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# Supavisor
VAULT_ENC_KEY=${VAULT_ENC_KEY}

# Studio
STUDIO_PG_META_URL=http://host.docker.internal:8080
SUPABASE_URL=http://localhost:8000
SUPABASE_PUBLIC_URL=http://localhost:8000

# MongoDB
MONGO_URI=mongodb://mongo:27017
MONGO_DB_NAME=mini_baas
MONGO_INITDB_ROOT_USERNAME=mongo
MONGO_INITDB_ROOT_PASSWORD=mongo

# Adapter Registry
ADAPTER_REGISTRY_DATABASE_URL=${DATABASE_URL}
ADAPTER_REGISTRY_URL=http://adapter-registry:3020
ADAPTER_REGISTRY_SERVICE_TOKEN=$(gen_alnum 32)

# Query Router
QUERY_ROUTER_URL=http://query-router:4001

# SMTP (local dev uses mailpit)
SMTP_HOST=mailpit
SMTP_PORT=1025
SMTP_USER=
SMTP_PASS=
SMTP_SECURE=false
EMAIL_FROM=noreply@mini-baas.local

# OAuth: Google (set real values for production)
GOOGLE_OAUTH_ENABLED=false
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# OAuth: GitHub
GITHUB_OAUTH_ENABLED=false
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=

# OAuth: 42 School
FORTYTWO_OAUTH_ENABLED=false
FORTYTWO_CLIENT_ID=
FORTYTWO_CLIENT_SECRET=

# WAF (public HTTP entrypoint — non-privileged port to avoid bind conflicts)
WAF_HTTP_PORT=8880

# Vault (empty = disabled; services fall back to env vars)
VAULT_ADDR=
VAULT_PORT=8200

# Logging
LOG_LEVEL=info

# Analytics Service
ANALYTICS_MONGO_DB=mini_baas_analytics
ANALYTICS_RETENTION_DAYS=90

# GDPR Service
GDPR_DELETION_WEBHOOK_URL=
GDPR_EXPORT_WEBHOOK_URL=

# Newsletter Service
NEWSLETTER_BATCH_SIZE=5

# AI Service
AI_MONGO_DB=mini_baas_ai
LLM_API_URL=https://api.groq.com/openai/v1
LLM_API_KEY=
LLM_MODEL=llama-3.3-70b-versatile
LLM_MAX_TOKENS=2048
LLM_TEMPERATURE=0.7
AI_CONVERSATION_TTL_HOURS=24

# Log Service
LOG_BUFFER_SIZE=1000
LOG_STREAM_TOKEN=$(gen_alnum 32)

# Session Service
SESSION_TTL_DAYS=7

# Frontend SPA
FRONTEND_PORT=5173
FRONTEND_URL=http://localhost:5173
EOF

chmod 600 "$ENV_FILE"
echo "Generated $ENV_FILE"
