use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Content type of an event's payload bytes.
///
/// # Purpose
/// Serializes as MIME strings for interoperability. JSON is the default.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum PayloadEncoding {
    /// JSON payload (`application/json`).
    #[serde(rename = "application/json")]
    #[default]
    Json,
    /// `MessagePack` payload (`application/msgpack`).
    #[serde(rename = "application/msgpack")]
    MsgPack,
    /// Opaque binary payload (`application/octet-stream`).
    #[serde(rename = "application/octet-stream")]
    Binary,
}

/// Classification of where an event originated.
///
/// # Purpose
/// Helps consumers distinguish CDC events from API-published or
/// scheduled events.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceKind {
    /// Published via the REST or WebSocket API.
    Api,
    /// Generated by a database change (CDC).
    Database,
    /// Generated by a periodic scheduler / cron job.
    Scheduler,
    /// Ingested from an external webhook.
    Webhook,
    /// Application-defined source kind.
    Custom(String),
}

/// Provenance information attached to an event.
///
/// # Purpose
/// Carries the source kind, a human-readable producer ID, and
/// optional key-value metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventSource {
    /// What kind of system produced this event.
    pub kind: SourceKind,
    /// Human-readable identifier of the producer.
    pub id: String,
    /// Free-form metadata attached by the producer.
    #[serde(default)]
    pub metadata: HashMap<String, String>,
}
