sonar.organization=univers42
sonar.projectKey=Univers42_mini-baas-infra
sonar.projectName=mini-baas-infra

sonar.host.url=https://sonarcloud.io

sonar.sources=docker/services,scripts,config,src/apps,src/libs
sonar.tests=
sonar.inclusions=**/*.js,**/*.ts,**/*.sh,**/*.sql,**/*.yml,**/*.yaml,**/*.py

sonar.exclusions=**/node_modules/**,**/vendor/**,**/sandbox/**,**/dist/**,**/coverage/**,.github/**,src/tools/**,src/Dockerfile,scripts/migrations/**,scripts/phase*-test.*,scripts/postgres-mvp-flow.sh,scripts/smoke-test-*.sh,docker/services/**/Dockerfile,docker/services/vault/scripts/**,**/pnpm-lock.yaml,**/*.min.js,**/*.min.css

sonar.javascript.file.suffixes=.js
sonar.typescript.file.suffixes=.ts
sonar.python.file.suffixes=.py

sonar.sourceEncoding=UTF-8
